import { type Topic } from "./icJoshiQuestions";

// Oxford Radio Navigation — Ch 14: SSR (Revision Q117-123)
export const oxfordRadNavCh14Topic: Topic = {
  id: "oxford-radnav-ch14",
  title: "Ch 12 – Secondary Surveillance Radar (SSR)",
  questions: [
    {
      id: 1,
      question: "The advantages of SSR mode S are:",
      options: [
        "improved resolution, TCAS",
        "data link, reduced voice communications",
        "TCAS, no RT communications",
        "better resolution, selective interrogation",
      ],
      correct: 1,
    },
    {
      id: 2,
      question: "The accuracy of SSR mode C altitude as displayed to the air traffic controller is:",
      options: ["+/-25 ft", "+/-50 ft", "+/-75 ft", "+/-100 ft"],
      correct: 1,
    },
    {
      id: 3,
      question: "The SSR ground transceiver interrogates on ................ and receives responses on ............",
      options: ["1030 MHz, 1030 MHz", "1030 MHz, 1090 MHz", "1090 MHz, 1030 MHz", "1090 MHz, 1090 MHz"],
      correct: 1,
    },
    {
      id: 4,
      question: "The vertical position provided by SSR mode C is referenced to:",
      options: ["QNH unless QFE is in use", "1013.25 hPa", "QNH", "WGS84 datum"],
      correct: 1,
    },
    {
      id: 5,
      question: "Why is a secondary radar display free from weather clutter?",
      options: [
        "The frequencies are too low to detect water droplets",
        "The frequencies are too high to detect water droplets",
        "Moving target indication is used to suppress the static generated by water droplets",
        "The principle of the return of echoes is not used",
      ],
      correct: 3,
    },
    {
      id: 6,
      question: "The availability of 4096 codes in SSR is applicable to mode:",
      options: ["A", "C", "S", "all"],
      correct: 3,
    },
    {
      id: 7,
      question: "With reference to SSR, what code is used to indicate transponder altitude failure?",
      options: ["9999", "0000", "4096", "7600"],
      correct: 1,
    },
  ],
};

// Oxford Radio Navigation — Ch 15: DME (Revision Q43-61)
export const oxfordRadNavCh15Topic: Topic = {
  id: "oxford-radnav-ch15",
  title: "Ch 13 – Distance Measuring Equipment (DME)",
  questions: [
    {
      id: 1,
      question: "Which of the following provides distance information?",
      options: ["DME", "VOR", "ADF", "VDF"],
      correct: 0,
    },
    {
      id: 2,
      question: "Which of the following would give the best indication of speed?",
      options: [
        "A VOR on the flight plan route",
        "A VOR off the flight plan route",
        "A DME on the flight plan route",
        "A DME off the flight plan route",
      ],
      correct: 2,
    },
    {
      id: 3,
      question: "What happens when a DME in the search mode fails to achieve lock-on?",
      options: [
        "It stays in the search mode, but reduces to 60 pulse pairs per second (ppps) after 100 seconds",
        "It stays in the search mode, but reduces to 60 ppps after 15000 pulse pairs",
        "It stays in the search mode at 150 ppps",
        "It alternates between search and memory modes every 10 seconds",
      ],
      correct: 1,
    },
    {
      id: 4,
      question: "The most accurate measurement of speed by DME for an aircraft at 30,000 ft will be when the aircraft is:",
      options: [
        "tracking towards the beacon at 10 NM",
        "overhead the beacon",
        "tracking away from the beacon at 100 NM",
        "passing abeam the beacon at 5 NM",
      ],
      correct: 2,
    },
    {
      id: 5,
      question: "A DME beacon will become saturated when more than about ............... aircraft are interrogating the transponder.",
      options: ["10", "50", "100", "200"],
      correct: 2,
    },
    {
      id: 6,
      question: "A typical DME frequency is:",
      options: ["1000 MHz", "1300 MHz", "1000 kHz", "1575 MHz"],
      correct: 0,
    },
    {
      id: 7,
      question: "The DME in an aircraft, cruising at FL210, fails to achieve lock-on a DME at MSL at a range of 210 NM. The reason for this is:",
      options: [
        "the beacon is saturated",
        "the aircraft is beyond the maximum usable range for DME",
        "the aircraft is beyond line of sight range",
        "the aircraft signal is too weak at that range to trigger a response",
      ],
      correct: 2,
    },
    {
      id: 8,
      question: "The aircraft DME receiver accepts replies to its own transmissions but rejects replies to other aircraft transmissions because:",
      options: [
        "the PRF of the interrogations is unique to each aircraft",
        "the pulse pairs from each aircraft have a unique amplitude modulation",
        "the interrogation frequencies are 63 MHz different for each aircraft",
        "the interrogation and reply frequencies are separated by 63 MHz",
      ],
      correct: 0,
    },
    {
      id: 9,
      question: "When an aircraft at FL360 is directly above a DME, at mean sea level, the range displayed will be:",
      options: ["6 NM", "9 NM", "0", "12 NM"],
      correct: 0,
    },
    {
      id: 10,
      question: "A DME frequency could be:",
      options: ["10 MHz", "100 MHz", "1000 MHz", "10,000 MHz"],
      correct: 2,
    },
    {
      id: 11,
      question: "An aircraft at FL360 is 10 NM plan range from a DME. The DME reading in the aircraft will be:",
      options: ["8 NM", "11.7 NM", "10 NM", "13.6 NM"],
      correct: 1,
    },
    {
      id: 12,
      question: "A DME transceiver does not lock onto its own reflections because:",
      options: [
        "the PRF of the pulse pairs is jittered",
        "it uses MTI",
        "the interrogation and reply frequencies differ",
        "the reflections will all fall within the flyback period",
      ],
      correct: 2,
    },
    {
      id: 13,
      question: "What information does military TACAN provide for civil aviation users?",
      options: ["Magnetic bearing", "DME", "Nothing", "DME and magnetic bearing"],
      correct: 1,
    },
    {
      id: 14,
      question: "The DME in an aircraft flying at FL430 shows a range of 15 NM from a beacon at an elevation of 167 ft. The plan range is:",
      options: ["13.5 NM", "16.5 NM", "15 NM", "17.6 NM"],
      correct: 0,
    },
    {
      id: 15,
      question: "What are the DME frequencies?",
      options: ["1030 & 1090 MHz", "1030 – 1090 MHz", "960 & 1215 MHz", "960 – 1215 MHz"],
      correct: 3,
    },
    {
      id: 16,
      question: "The time from the transmission of the interrogation pulse to the receipt of the reply from the DME ground station is 2000 microseconds (ignore the delay at the DME). The slant range is:",
      options: ["330 NM", "185 NM", "165 NM", "370 NM"],
      correct: 2,
    },
    {
      id: 17,
      question: "The DME counters are rotating continuously. This indicates that:",
      options: [
        "the DME is unserviceable",
        "the DME is trying to lock onto range",
        "the DME is trying to lock onto frequency",
        "the DME is receiving no response from the ground station",
      ],
      correct: 1,
    },
    {
      id: 18,
      question: "On a DME presentation the counters are continuously rotating. This indicates:",
      options: [
        "the DME is in the search mode",
        "the DME is unserviceable",
        "the DME is receiving no response from the transponder",
        "The transponder is unserviceable",
      ],
      correct: 0,
    },
    {
      id: 19,
      question: "An aircraft at FL200 is 220 NM from a DME at MSL. The aircraft equipment fails to lock on to the DME. This is because:",
      options: [
        "DME is limited to 200 NM",
        "the aircraft is too high to receive the signal",
        "the aircraft is too low to receive the signal",
        "the beacon is saturated",
      ],
      correct: 2,
    },
  ],
};
